name: Deploy to Google

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ master ]


jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build:prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.GCLOUD_TOKEN }}